require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'vndt' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
#  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"


  target 'vndtTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end


end

target 'vndt-tvOS' do
  # Pods for vndt-tvOS

  target 'vndt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
